### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/WEEEhire-ng#32]
The deployment of this website is a long process, between package installations and configs. 
A Dockerfile would allow for a very quick deployment.

The [nginx Docker image](https://hub.docker.com/_/nginx) may be a nice place to start.

**Comment by lvps** [comment]
@e-caste Also remember to leave the sqlite file outside of the container, or make it permanent. Somehow. asd

**Comment by e-caste** [comment]
@lvps Good idea, the ADD command does exactly that.

**Comment by e-caste** [comment]
Closed with PR #51
