### ISSUE TITLE
Remove recruiter nickname from interview email signature

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/WEEEhire-ng#45]
I don't think it's very professional to send our nickname to new people

**Comment by lvps** [comment]
Just to be clear, leaving it in the "please contact me on telegram, my nickname is ..." part is acceptable, right?

Having it in the signature is unprofessional, I agree, it's even probably a bug as I should have used the name

**Comment by e-caste** [comment]
@lvps Well, our Telegram contact is needed for new people to contact us, so yes, I’m referring to the email signature only
