### ISSUE TITLE
Solve database error when submitting application

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/WEEEhire-ng#71]
With docker-compose, locally. Sqlite should just work, right?

**Comment by lvps** [comment]
@e-caste Yes. It works on my machine too, so I need a stack trace for that (it's printed to stderr) asd

**Comment by e-caste** [comment]
Okay, I have tested many interactions involving the db and as of the latest commit I cannot see any error even with docker-compose. Closing this issue.
