### ISSUE TITLE
It seems like the study courses can be injected

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/WEEEhire-ng#79]
![image](https://user-images.githubusercontent.com/27449310/138011300-a260d798-ee31-4fde-a0e4-0a5368d4f035.png)

The screenshot shows the JSON data that I downloaded after I successfully applied as
a person who is doing a doctostochastic in "Architettura del Lollone".

Is this a feature or a bug? asd

**Comment by steemnd** [comment]
@lvps loll1
