### ISSUE TITLE
Separate text boxes for comments by each recruiter

### ISSUE THREAD

**Issue by alecello** [WEEE-Open/WEEEhire-ng#81]
Have each reviewer put a star rating and an optional description when submitting a review for a candidate, and display these two elements together for each reviewer in a compact way:

- If no text has been supplied, just show name of recuiter and star rating next to it
- If text has been supplied, show it below the name + rating
- Have recruiter name in bold and maybe review text jusstified to the right a bit

**Comment by lvps** [comment]
Done but not as compact, open another issue if you want to move the star rating (placing that into the table will be and endless nightmare)
